name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install pyyaml xmltodict pyinstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile project.py
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: program
          path: dist/project.exe